image: node:16-alpine

# Manage npm cache between jobs
cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

stages:
  - build
  - deploy

build:
  stage: build
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npx nx build i18n-web --c production
    - npx nx build i18n-backend --c production
    - mv node_modules dist/apps/i18n-backend
    - cp package.json dist/apps/i18n-backend
    - cp apps/i18n-backend/ormconfig.prod-cli.json dist/apps/i18n-backend
    - cp apps/i18n-backend/.env.prod dist/apps/i18n-backend
  artifacts:
    untracked: false
    expire_in: 3 days
    paths:
      - dist/apps/i18n-web
      - dist/apps/i18n-backend

deploy:
  stage: deploy
  needs:
    - build
  script:
    - echo "cd dist/apps/i18n-backend && npm run migration:run:prod"
    - echo "Upload dist/apps/i18n-backend to node executor && node main.js"
    - echo "Upload dist/apps/i18n-web to web storage"