image: node:16-alpine

stages:
  - install dependencies
  - build
  - deploy

install dependencies:
  stage: install dependencies
  cache:
    key: 'i18n-dependencies-cache'
    policy: 'pull-push'
    paths:
      - node_modules/
  script:
    - ls -la
    - npm install
    - ls -la

build i18n-web:
  stage: build
  cache:
    key: 'i18n-dependencies-cache'
  needs:
    - install dependencies
  script:
    - ls -la
    - npx nx build i18n-web --c production
    - ls -la
    - ls -la dist/apps/i18n-web
  artifacts:
    untracked: false
    expire_in: 3 days
    paths:
      - dist/apps/i18n-web

build i18n-backend:
  stage: build
  cache:
    key: 'i18n-dependencies-cache'
  needs:
    - install dependencies
  script:
    - ls -la
    - npx nx build i18n-backend --c production
    - cp package.json dist/apps/i18n-backend
    - cp apps/i18n-backend/ormconfig.prod-cli.json dist/apps/i18n-backend
    - cp apps/i18n-backend/.env dist/apps/i18n-backend
    - ls -la
    - ls -la dist/apps/i18n-backend
  artifacts:
    untracked: false
    expire_in: 3 days
    paths:
      - dist/apps/i18n-backend

deploy i18n-web:
  stage: deploy
  needs:
    - build i18n-web
  script:
    - ls -la

deploy i18n-backend:
  stage: deploy
  cache:
    key: 'i18n-dependencies-cache'
  needs:
    - build i18n-backend
  script:
    - ls -la