branch-defaults:
  default:
    environment: Kizeoi18n-dev
environment-defaults:
  Kizeoi18n-dev:
    branch: null
    repository: null
global:
  application_name: kizeo-i18n
  default_region: eu-west-3
  include_git_submodules: false
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
deploy:
  artifact: data.zip
